import { defineConfig } from 'orval';

export default defineConfig({
	api: {
		input: './openapi.yaml',
		output: {
			client: 'react-query',
			mode: 'single',
			target: './src/generated/api.ts',
			httpClient: 'axios',
			override: {
				query: {
					useQuery: true,
					useMutation: true,
					useSuspenseQuery: true,
				},
				mutator: {
					path: './src/services/api-client.ts',
					name: 'customInstance',
				},
				header: (info) => [
					`Generated by orval 🍺`,
					`Do not edit manually.`,
					...(info.title ? [info.title] : []),
					...(info.description ? [info.description] : []),
					...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
					'eslint-disable',
				],
			},
		},
	},
});
